export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const ADD_INFO_MESSAGE = "ADD_INFO_MESSAGE";
export const REMOVE_INFO_MESSAGE = "REMOVE_INFO_MESSAGE";

export const SET_NEW_USER = "SET_NEW_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_ALL_USERS_EXPECT_CURRENT = "GET_ALL_USERS_EXPECT_CURRENT";

export const SET_USER_AVATAR = "SET_USER_AVATAR";

export const LOAD_MESSAGES = "LOAD_MESSAGES";
