export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const ADD_INFO_MESSAGE = "ADD_INFO_MESSAGE";
export const REMOVE_INFO_MESSAGE = "REMOVE_INFO_MESSAGE";

export const CREATE_USER = "CREATE_USER";
export const SET_USER_SOCKET_ID = "SET_USER_SOCKET_ID";

export const GET_ALL_USERS_EXPECT_CURRENT = "GET_ALL_USERS_EXPECT_CURRENT";

export const SET_USER_AVATAR = "SET_USER_AVATAR";

export const SET_NEW_ROOM = "SET_NEW_ROOM";
export const SET_CURRENT_ROOM = "SET_CURRENT_ROOM";
export const LOAD_MESSAGES = "LOAD_MESSAGES";

export const NEW_MESSAGE = "NEW_MESSAGE";
